/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file.
// Regenerate it by running `npx @tanstack/router-cli generate`.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";

const IndexRoute = IndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRoute,
});

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
}

export interface FileRoutesByTo {
    "/": typeof IndexRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    "/": typeof IndexRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/";
    fileRoutesByTo: FileRoutesByTo;
    to: "/";
    id: "__root__" | "/";
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
