export enum JourneyStatus {
    PLANNED = "PLANNED",
    AWAITING_LOADING = "AWAITING_LOADING",
    AWAITING_DEPARTURE = "AWAITING_DEPARTURE",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
}
